lo1tuma/eslint-plugin-mocha

.travis.yml

With this change, the build should run sooner on travis-ci (see: http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/).

Disable sudo on travis-ci

---

docs/rules/README.md
docs/rules/handle-done-callback.md
index.js
lib/rules/handle-done-callback.js
package.json
test/rules/handle-done-callback.js

For now the rule performs a really simple check and may not cover each
possible use-case.
* It doesn’t include branch-tracking to make sure that the `done` callback is called in every possible branch.
* It doesn’t check **HOW** the callback is handled, so e.g. `return done;` would be sufficient.

Add new rule handle-done-callback

---

docs/rules/no-synchronous-tests.md
lib/rules/no-synchronous-tests.js
test/rules/no-synchronous-tests.js

I've had a need for a rule based on my experience writing a bunch of async tests within mocha. This rule checks that either a callback was specified or that a promise was returned in the test function.
Mocha dynamically determines whether a test is synchronous by whether the function includes a callback or returns a promise. Because of that, it's easy to end up in a situation where you intend to return a promise (and do not have a `done` callback) but accidentally omit the `return` statement. This leads to a false-positive where the test would automatically succeed regardless of the actual async result.
This rule works well side-by-side with `handle-done-callback`, as that rule will enforce whether or not a callback was actually called.
Let me know if you see any issues with this PR and …

Add no-synchronous-tests rule

---

index.js
test/rules/handle-done-callback.js
test/rules/no-exclusive-tests.js
test/rules/no-synchronous-tests.js

Closes #27
Hopefully the test changes aren't disagreeable.  I think this is a good way to make sure `index.js` doesn't get missed.

add new rule to index.js and change tests to keep that from happening

---

lib/rules/handle-done-callback.js
test/rules/handle-done-callback.js

Improve detection if done callback is handled

---

docs/rules/README.md
docs/rules/no-skipped-tests.md
index.js
lib/rules/no-skipped-tests.js
test/rules/no-skipped-tests.js

Add a rule to catch skipped tests (e.g. `describe.skip()` or `xdescribe`).

Add rule no-skipped-tests

---

docs/rules/README.md
docs/rules/no-pending-tests.md
index.js
lib/rules/no-pending-tests.js
test/rules/no-pending-tests.js

Implements [#51](https://github.com/lo1tuma/eslint-plugin-mocha/issues/51)

Add rule no-pending-tests

---

lib/rules/no-exclusive-tests.js
test/rules/no-exclusive-tests.js

Thanks for this project! 
I would like to suggest an improvement that is relevant to me: I have setup my editor to auto-fix eslint errors on save. When the exclusive tests rule is auto-fixable, I lose the ability to single out tests. 
Fixes #60

Remove autofix on no-exclusive-tests rule. 

---

docs/rules/README.md
docs/rules/valid-suite-description.md
index.js
lib/rules/valid-suite-description.js
test/rules/valid-suite-description.js

feat(rules): add 'valid-suite-description' rule

---

docs/rules/README.md
docs/rules/no-mocha-arrows.md
index.js
lib/rules/no-mocha-arrows.js
test/rules/no-mocha-arrows.js

no-mocha-global-arrows: New rule

---

docs/rules/no-exclusive-tests.md
docs/rules/no-skipped-tests.md
lib/rules/no-exclusive-tests.js
lib/rules/no-skipped-tests.js
lib/util/settings.js
test/rules/no-exclusive-tests.js
test/rules/no-skipped-tests.js

This feature is useful if using this plugin with a package like `ember-mocha`, which provides its own set of `describe` functions. A custom array can be provided so that those extensions can also be protected from having `only` called.
One thought about my changes is that it introduces a configuration object rather than an array.  We could make the option parameter just an array, but I kind of like the extra context provided by the named keys.  The difference is basically between this (how I have it right now)
```json
{
"rules": {
"mocha/no-exclusive-tests": ["error", {
"additionalTestFunctions": [
"describeModule"
]
}]
}
}
```
and this (which I think provides less context and it more confusing)
```json
{
"rules": {
"mocha/no-exclusive-tests": ["error", [
"describeModule"
]]
}
}
``` …

Allow custom test functions

---

docs/rules/README.md
docs/rules/no-sibling-hooks.md
index.js
lib/rules/no-sibling-hooks.js
test/rules/no-sibling-hooks.js

Add rule `no-sibling-hooks` (fixes #82)
Let me know if you want me to change something or if I've missed something :)
I deactivatd two rules [here](https://github.com/lo1tuma/eslint-plugin-mocha/pull/85/files#diff-23841b5a313e8e46a51f3d758eaa6f4fR22) about the function complexity. I could not make the function less complex. I could move the last part of the function to another function, but I'm not sure it would make it less complex, as you'd pass a few arguments around. Not opposed to doing that though. Let me know what you wish for me to do.

Add rule `no-sibling-hooks` (fixes #82)

---

docs/rules/README.md
docs/rules/no-sibling-hooks.md
docs/rules/no-top-level-hooks.md
index.js
lib/rules/no-hooks.js
lib/rules/no-sibling-hooks.js
lib/rules/no-top-level-hooks.js
lib/util/ast.js
test/rules/no-top-level-hooks.js

Add `no-top-level-hooks` rule (fixes #37)
Since this rule has a lot of common code with `no-hooks` and `no-sibling-hooks`, I refactored them all to use common methods. It's all much cleaner now, but it might be a lot to look at for one PR. Let me know if you wish for me to split this PR up into two (one for the work on this rule and one for the refactoring)

Add `no-top-level-hooks` rule (fixes #37)

---

docs/rules/README.md
docs/rules/no-return-and-callback.md
index.js
lib/rules/no-return-and-callback.js
test/index.js
test/rules/no-return-and-callback.js

Add rule `no-return-and-callback` (fixes #88)
Still needs to be validated, but thought I might as well make the PR as I have already written the rule. As said in the issue, I think it's better to warn when we return something, and not only if we can be sure it's a Promise that is being returned.
By the way, this rule will also warn for the same pattern in hooks. The [Mocha changelog](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#boom-breaking-changes) only mentionned this new behavior for tests, but after trying it out, I confirm it also applies to hooks.

Add rule `no-return-and-callback` (fixes #88)

---

docs/rules/README.md
docs/rules/no-identical-title.md
index.js
lib/rules/no-identical-title.js
test/rules/no-identical-title.js

Add `no-identical-title` rule (fixes #33)
I decided to name it `no-identical-title` to be "consistent" with `eslint-plugin-ava`'s [similar rule](https://github.com/avajs/eslint-plugin-ava/blob/master/docs/rules/no-identical-title.md). Let me know if you prefer it to be `no-duplicate-title` or something else.

Add `no-identical-title` rule (fixes #33)

---

lib/rules/no-identical-title.js
test/rules/no-identical-title.js

Fix crash in no-identical-title (fixes #98)
The problem was no new test suite "layer" was added if the test suite had a non-string literal title, but the layers were popped regardless of the title, which resulted in an empty stack.
cc @epmatsw

Fix crash in no-identical-title (fixes #98)

---

docs/rules/valid-suite-description.md

Adds rule name to title for `valid-suite-description` documentation.

---

docs/rules/README.md
docs/rules/no-nested-tests.md
index.js
lib/rules/no-nested-tests.js
lib/util/ast.js
test/rules/no-nested-tests.js

Add no-nested-tests rule

---

CHANGELOG.md

Looks like `max-top-level-suites` was at one point named `one-suite-per-file`, but that was changed before release. The CHANGELOG was never updated, which makes it kind of hard to figure out what actually was changed. This PR just fixes the changelog to match the actual change that was made.

Fix rule name in CHANGELOG to match actual rule

---

lib/rules/no-mocha-arrows.js
test/rules/no-mocha-arrows.js

I make `no-mocha-arrows` rule fixable with `--fix` option of `eslint` command.
- Before
``` js
it("does something", () => { assert.ok(true); });
it("does something", () => assert.ok(true));
```
- After
``` js
it("does something", function () { assert.ok(true); });
it("does something", function () { return assert.ok(true); });
```
EDIT: Translation result of single expression body

Make no-mocha-arrows rule fixable

---

lib/rules/no-mocha-arrows.js
test/rules/no-mocha-arrows.js

When a test implementation has parameters, the end result would have missing parens.
```js
it(done => {});
// -->
it(function done {});
```
This fixes it. I could not keep a consistent spacing for `function () {}` and `function() {}`, so I modified the current results, but when fixing, that will probably be taken care of the other rules' fixers anyway.
cc @rhysd if you feel like reviewing

Fix no-mocha-arrow fixer

---

lib/rules/max-top-level-suites.js
lib/rules/no-hooks-for-single-case.js
lib/rules/no-identical-title.js
lib/rules/no-nested-tests.js
lib/rules/no-sibling-hooks.js
lib/rules/no-top-level-hooks.js
lib/util/ast.js
lib/util/settings.js
test/rules/max-top-level-suites.js
test/rules/no-hooks-for-single-case.js
test/rules/no-identical-title.js
test/rules/no-nested-tests.js
test/rules/no-sibling-hooks.js
test/rules/no-top-level-hooks.js

This PR adds a new shared settings value which accepts an array of additional suite names, for example:
`
"settings": {
"mocha/additionalSuiteNames': [ 'foo', 'bar' ],
}
`
This is useful when working with modules like [mocha.parallel](https://github.com/danielstjules/mocha.parallel)
@lo1tuma let me know what you think and I'll adapt it for the following rules as well.

Add settings to enable support for mocha.parallel

---

package.json

unless i'm missing something there's no reason to drop this?

don't drop support for eslint 3.x

---

docs/rules/no-synchronous-tests.md
lib/rules/no-synchronous-tests.js
test/rules/no-synchronous-tests.js

One note: the updated rule throws errors when the provided options do not match a certain format.
eslint itself usually does not test those exception cases (it ignores them for code coverage: https://github.com/eslint/eslint/blob/master/lib/rules/new-cap.js#L38) and I wasn't sure how to test an exception with the RuleTester so I ignored those cases as well.

Added support for async functions in no-synchronous-tests

---

.travis.yml

In order to use more modern language feature I’m going to plan removing nodejs 4 support with next major release.
Alongside we will also drop support for nodejs 5 and 7 which are end-of-life anyway.

Remove support for nodejs 4, 5 and 7

---

README.md
package.json

AFAIK there is nothing breaking with ESLint versions < 4.0.0 yet but I think it would make sense to get rid of supporting those versions in order to keep maintenance of this project easy.

Remove support for ESLint versions < 4.0.0

---

docs/rules/README.md
docs/rules/prefer-arrow-callback.md
index.js
lib/rules/prefer-arrow-callback.js
test/rules/prefer-arrow-callback.js

Addresses #141 
---
- Copied core eslint `prefer-arrow-callback` rule code, test code, and markdown doc from: https://github.com/eslint/eslint/blob/master/docs/rules/prefer-arrow-callback.md
- Modified this rule to be mocha-aware by utilizing the exiting utility function `astUtils.isMochaFunctionCall(node, scope)`
- Updated tests to include *rule not triggered* tests for all mocha functions
- Updated documentation to include instructions to disable the core `prefer-arrow-callback` rule before enabling the `mocha/prefer-arrow-callback` rule
The following eslint rules are failing with this code:
```
/Users/mfields/workspace/eslint-plugin-mocha/lib/rules/prefer-arrow-callback.js
90:1   error  Function 'getCallbackInfo' has a complexity of 12                                     complexity …
```

Adds mocha-aware prefer-arrow-callback rule

---

lib/rules/no-nested-tests.js
lib/util/ast.js
test/rules/no-nested-tests.js

This is just a quick implementation to see if there's any interest. And yes, this actually happened :)
Questions:

Prohibit tests in beforeEach etc. hook calls

---

docs/rules/max-top-level-suites.md
docs/rules/no-synchronous-tests.md
docs/rules/valid-suite-description.md
docs/rules/valid-test-description.md

```
Configuration for rule "mocha/valid-test-description" is invalid:
Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"warning"').
```

Replace `warning` with `warn`

---

lib/rules/prefer-arrow-callback.js
test/rules/prefer-arrow-callback.js

`new.target` is only allowed in functions, when it’s used elsewhere we will get a parsing error.
I’ve also removed the unnecessary if statement in the rule as we can’t test the else branch because it is unreachable.

Fix invalid syntax in test case

---

docs/rules/README.md
docs/rules/no-async-describe.md
index.js
lib/rules/no-async-describe.js
test/rules/no-async-describe.js

I've seen `describe('my test', async function () { ... })` cause subtle problems, so I think it makes sense to add a rule for it.

Implement no-async-describe rule

---

lib/rules/no-setup-in-describe.js
test/rules/no-setup-in-describe.js

Fix no-setup-in-describe to work with arrow functions

---

lib/rules/no-setup-in-describe.js
lib/util/ast.js
test/rules/no-setup-in-describe.js

There was one call of `astUtils.isDescribe` which has been called without the second parameter which caused the function to accept `undefined` as a valid alias for suite function names. Additionally there are cases where we don’t get a node name for `CallExpressions` (e.g. `foo()()`). So in such cases the extracted node name is `undefined` and `isDescribe` will return true due to the above mentioned
bug.
Fixes: #172

Fix no-setup-in-describe to correctly detect describe calls

---

README.md
index.js

Added recommended ruleset

---

docs/rules/README.md
docs/rules/no-return-from-async.md
index.js
lib/rules/handle-done-callback.js
lib/rules/no-return-and-callback.js
lib/rules/no-return-from-async.js
lib/rules/no-synchronous-tests.js
lib/util/ast.js
test/rules/no-return-from-async.js

While upgrading a codebase to use async/await I've found it to be a bit confusing when the two Promise styles are mixed so a Promise is returned from an `async` test:
```js
it('should foo', async function () {
await bar();
return expect(somePromise).to.eventually.be.rejectedWith('bla');
});
```
I've implemented a rule that prohibits mixing these two styles, similar to to the `no-return-and-callback`. And pretty much all copy/pasted from it because of the similarities :)

Implement no-return-from-async rule

---

docs/rules/valid-test-description.md
lib/rules/valid-test-description.js
test/rules/valid-test-description.js

Add the possibility to define a custom error message to explain the pattern. There is two ways to define this message, sending it inline after `testNames` or by providing an object with the property `message`.
If this PR passes, I'll do the same for `valid-suite-description`
Fixes #204

Add custom message for valid-test-description rule

---

docs/rules/valid-suite-description.md
lib/rules/valid-suite-description.js
test/rules/valid-suite-description.js

Add custom message for valid-suite-description

---

.eslintrc.json
benchmarks/startup.bench.js
lib/rules/handle-done-callback.js
lib/rules/max-top-level-suites.js
lib/rules/no-mocha-arrows.js
lib/rules/no-synchronous-tests.js
lib/util/ast.js
package.json

Startup Performance Optimization

---

lib/rules/no-synchronous-tests.js
test/rules/no-synchronous-tests.js

Relax no-synchronous-tests to allow non literals from concise arrows

---

.github/workflows/ci.yml

This ensures that Coveralls will be notified about the build **after** the last matrix job is finished

✉️ Send a webhook to Coveralls when the build completes

---

index.js

Fix alphabetization within config rule list and alphabetize rule list (for easier comparison to ensure no rules are missing in either list).
Also adds `'mocha/no-return-from-async': 'off',` to `recommended` config for consistency (since all other rules are included in the list).

Alphabetize rule lists

---

index.js

add plugin to recommended config, so it's not necessary to explicitly add the plugin when using this config.
this is the default for every major eslint plugin with recommended configs, ex:
- `eslint-plugin-node`
- `eslint-plugin-react`
- `eslint-plugin-import`
- `eslint-plugin-jsx-a11y`
- `eslint-plugin-jest`
- `eslint-plugin-promise`
- `eslint-plugin-vue`
- `eslint-plugin-prettier`
- and others.

add plugin to recommended config

---

docs/rules/README.md
docs/rules/no-async-describe.md
docs/rules/no-mocha-arrows.md
docs/rules/prefer-arrow-callback.md
lib/rules/no-async-describe.js
lib/rules/no-mocha-arrows.js
lib/rules/no-skipped-tests.js

Per docs at https://eslint.org/docs/developer-guide/working-with-rules :
"Without the fixable property, ESLint does not apply fixes even if the rule implements fix functions. Omit the fixable property if the rule is not fixable."
Also fixes one non-alphetizated rule.
I've also switched to the [non-deprecated](https://eslint.org/blog/2016/07/eslint-new-rule-format). I could also add for the other rules as well, but in this PR I've only changed those where it was a natural change as a part of adding the `fixable` property.

Add `fixable` property to fixable rules (and mention in docs)

---

lib/rules/valid-suite-description.js
lib/rules/valid-test-description.js

The `u` flag is supported per the Node >= 8.0.0 targeted versions of your `engines`, so thought I'd just follow the growing practice of using this flag by default for Unicode friendliness. 
Could be a breaking change where someone had an unescaped opening curly bracket in a regex, but would presumably not affect most users/cases.

Add `u` flag in RegExp for `valid-test-description` and `valid-suite-description`

---

docs/rules/max-top-level-suites.md
docs/rules/no-exclusive-tests.md
docs/rules/no-hooks-for-single-case.md
docs/rules/no-skipped-tests.md
docs/rules/no-synchronous-tests.md
docs/rules/valid-suite-description.md
docs/rules/valid-test-description.md

Add "Options" heading in each doc file where options are available (and ensure consistent level 2 heading)

"Options" heading in doc files (and consistent level 2 heading)

---

docs/rules/README.md
test/index.js

Builds on #228
- Indicate whether rule is recommended (also put into table along with info on whether "fixable")

Indicate whether rule is recommended

---

lib/rules/max-top-level-suites.js
lib/rules/no-exclusive-tests.js
lib/rules/no-hooks-for-single-case.js
lib/rules/no-skipped-tests.js
lib/rules/no-synchronous-tests.js
lib/rules/valid-suite-description.js
lib/rules/valid-test-description.js
test/rules/valid-suite-description.js
test/rules/valid-test-description.js

If you want me to keep the schemas for settings, I can instead comment them out, but AFAICT, they are only usable with options, not `settings`.
Note that I've had to comment out one test case in each of the two `valid-*-description` rules for this PR as the new schema causes some RegExp literals to fail on a couple properties (since *JSON* Schema can only specify JSON types and does not support indicating a `RegExp` except as a string).

Add schemas for options (and remove for files which are using settings)

---

lib/rules/handle-done-callback.js
lib/rules/no-global-tests.js
lib/rules/no-hooks.js
lib/rules/no-identical-title.js
lib/rules/no-nested-tests.js
lib/rules/no-pending-tests.js
lib/rules/no-return-and-callback.js
lib/rules/no-return-from-async.js
lib/rules/no-setup-in-describe.js
lib/rules/no-sibling-hooks.js
lib/rules/no-top-level-hooks.js

Builds on #228 and #234.
Completes move to [non-deprecated](https://eslint.org/blog/2016/07/eslint-new-rule-format) eslint rule format (mentioned first in #228).

Nondeprecated rule format

---

lib/rules/valid-suite-description.js
lib/rules/valid-test-description.js
lib/util/ast.js
package-lock.json
package.json
test/rules/valid-suite-description.js
test/rules/valid-test-description.js

Fixes: #139
Using [`getStringIfConstant()`] from [`eslint-utils`](https://eslint-utils.mysticatea.dev/api/ast-utils.html#getstringifconstant) this should now also support things like computed strings e.g. `it('should' + 'work', () => {});`.

Check static template strings in valid-test-description and valid-suite-description

---

lib/rules/no-hooks-for-single-case.js
test/rules/no-hooks-for-single-case.js

no-hooks-for-single-case: fix false postive in nested suites

---

docs/rules/no-nested-tests.md
lib/rules/handle-done-callback.js
lib/rules/max-top-level-suites.js
lib/rules/no-async-describe.js
lib/rules/no-exclusive-tests.js
lib/rules/no-global-tests.js
lib/rules/no-hooks-for-single-case.js
lib/rules/no-hooks.js
lib/rules/no-identical-title.js
lib/rules/no-mocha-arrows.js
lib/rules/no-nested-tests.js
lib/rules/no-pending-tests.js
lib/rules/no-return-and-callback.js
lib/rules/no-return-from-async.js
lib/rules/no-setup-in-describe.js
lib/rules/no-sibling-hooks.js
lib/rules/no-skipped-tests.js
lib/rules/no-synchronous-tests.js
lib/rules/no-top-level-hooks.js
lib/rules/prefer-arrow-callback.js
lib/rules/valid-suite-description.js
lib/rules/valid-test-description.js

add `meta.type` ("problem" or "suggestion") for use by `eslint --fix-type` or formatters and add missing "fixable: code" to `no-skipped-tests`

Add `meta.type` and missing `fixable: 'code'`

---

lib/rules/no-mocha-arrows.js
test/rules/no-mocha-arrows.js

Support comments in arrow functions when fixing

---

lib/rules/max-top-level-suites.js
test/rules/max-top-level-suites.js

Fix max-top-level-suites to work with ES modules

---

docs/rules/README.md
docs/rules/no-skipped-tests.md
lib/rules/no-skipped-tests.js
test/rules/no-skipped-tests.js

Remove autofix from rule `no-skipped-tests` as it alters the test runtime, and makes it impossible to use this rule as a warning
resolves #242

remove autofix from no-skipped-tests rule fix

---

lib/rules/prefer-arrow-callback.js
test/rules/prefer-arrow-callback.js

Fix prefer-arrow-callback to not fail when using import.meta

---

.github/workflows/ci.yml
benchmarks/measure.js
benchmarks/runtime.bench.js
benchmarks/startup.bench.js
package.json

Add benchmarks for runtime with many files

---

index.js

set `env.mocha: true` on recommended config, so it's not necessary to explicitly set it when using this config.
eslint documents this being done for plugins (the example code includes env settings on each config): https://eslint.org/docs/developer-guide/working-with-plugins#configs-in-plugins

set env.mocha on recommended config

---

benchmarks/measure.js
benchmarks/runtime.bench.js
package-lock.json
package.json

Since older node versions are not as fast as the latest node version we should take that into account and increase the performance budget for older node versions.
cc: @szuend

Improve benchmark test reliability

---

benchmarks/runtime.bench.js
lib/rules/no-exclusive-tests.js
lib/rules/no-pending-tests.js
lib/util/ast.js

The `isDescribe` and `isTestCase` are doing a lot of work that is unnecessarily redone on each call expression.
This PR moves this work upfront, when the rule is created and re-uses the result for each call expression.
Please note that the choosen implementation is not a strong opinion. I tried to keep the code churn to a minimum and not export more astUtils internals. Feel free to suggest how you prefer this to be solved differently.
We noticed the performance while linting the [DevTools frontend](https://chromium.googlesource.com/devtools/devtools-frontend/). Running with the following command line:
```sh
TIMING=1 third_party/node/node.py --output scripts/test/run_lint_check_js.js
```
Before the change:
```
Rule                                 | Time (ms) | Relative …
```

Speed up no-exclusive-tests and no-pending-tests

---

benchmarks/runtime.bench.js
lib/util/names.js
test/util/namesSpec.js

It looks like just memoizing `getNamesByType` speeds up the benchmark by more than 10x.
Closes #268.

Memoize names (increases speed by 10x)

---

.eslintrc.json
docs/rules/README.md
docs/rules/no-empty-description.md
index.js
lib/rules/no-empty-description.js
test/rules/no-empty-description.js

This rule enforces specifying the suite/test descriptions for each test. 
The following patterns are considered problems:
```js
it();
suite("");
test(function() { })
test.only(" ", function() { })
```
also, I added this rule to the recommendations list.

Add `no-empty-description` rule. closes #302

---

README.md

Quick PR to remove the https://david-dm.org badge from the README since this service is no longer available.

Remove unavailable badge from README

---

.github/workflows/ci.yml
package-lock.json
package.json

Adds popular tool [npm-run-all](https://www.npmjs.com/package/npm-run-all) for running scripts.
Benefits:
* Single script to run all types of linting in parallel (`run-p` is alias for `npm-run-all --parallel`)
* Uses double quotes instead of single quotes for better cross-platform support
* Uses npm-run-all instead of `&&` for better cross-platform support
> Cross platform. We sometimes use & to run multiple command in parallel, but cmd.exe (npm run-script uses it by default) does not support the &. Half of Node.js users are using it on Windows, so the use of & might block contributions. npm-run-all --parallel works well on Windows as well.

chore: use `npm-run-all` to run lint/test scripts

---

index.js

Fixes: Definition for rule 'no-empty-description' was not found

Add `mocha` prefix to "no-empty-description" rule name in rec config

---

.github/workflows/ci.yml

chore: switch yarn command to npm

---

docs/rules/README.md

`recommended` rules set include `warning` and `error` level rules.
Some team may rely on rules to prevent unwanted behavior, like the one addressed by `mocha/no-exclusive-tests`.
To make it work in CI, and not to rely on developer's local hooks, the default error level should be elevated from `warning` to `error`.  But to get this property, one has to dig into index.js
Add error level in rules documentation
Using emoticons may be more readable than text (maybe :warning: for `warning` and :bomb:  for `error`?)
Compare with `index.js`

Document recommended error level

---

test/rules/no-mocha-arrows.js

The changes made in #326 [here](https://github.com/lo1tuma/eslint-plugin-mocha/pull/326/files#r883383476) uncovered a code path not being verified by unit tests. This PR adds two tests that verify the correct `reference` is being used for the `isShadowed` check.

Add unit tests to verify the correct reference is analyzed for shadowing

---

.github/workflows/ci.yml
benchmarks/measure.js
benchmarks/runtime.bench.js
lib/rules/handle-done-callback.js
lib/rules/max-top-level-suites.js
lib/rules/no-synchronous-tests.js
lib/util/ast.js
lib/util/memoizeWith.js
lib/util/names.js
package-lock.json
package.json

Thanks to @jrandolf for the original PR #325 this is based off

Support Node 18 + switch from ramda to rambda

---

lib/util/ast.js
test/rules/no-exclusive-tests.js

A `ThisExpression` doesn't have a name so effectively, `this.it` is parsed as `undefined.it` and that works but is obviously wrong since it would also catch literally `undefined.it` as well.

Support this for additionalCustomNames

---

README.md
lib/util/ast.js
test/rules/max-top-level-suites.js
test/rules/no-async-describe.js
test/rules/no-exclusive-tests.js
test/rules/no-sibling-hooks.js
test/rules/no-skipped-tests.js
test/rules/no-top-level-hooks.js

Call expressions can have a name when getting the node. Fixes #335 
There might have been better ways to achieve this, but this looked like the most straightforward.

Support function calls as custom names (to stop false warnings)

---

README.md
docs/rules/consistent-spacing-between-blocks.md
index.js
lib/rules/consistent-spacing-between-blocks.js
test/rules/consistent-spacing-between-blocks.js

This PR introduces a new rule `mocha/consistent-spacing-between-blocks`, which enforces consistent line breaks between Mocha testing blocks (before, after, describe, it, beforeEach, afterEach) within describe blocks.
The following patterns are considered errors:
```javascript
describe("MyComponent", function () {
beforeEach(function () {
// setup code
});
it("should behave correctly", function () {
// test code
});
});
```
These patterns would not be considered errors:
```javascript
describe("MyComponent", function () {
beforeEach(function () {
// setup code
});
it("should behave correctly", function () {
// test code
});
afterEach(function () {
// teardown code
});
});
```
The motivation behind this rule is to improve the readability of test code, making it easier to distinguish …

Add `consistent-spacing-between-blocks` rule

---

.c8rc.json
source/ast/node-types.ts
source/rules/consistent-spacing-between-blocks.test.ts
source/rules/consistent-spacing-between-blocks.ts

Fix consistent-spacing-between-blocks when using timeout() modifier

---

source/rules/no-synchronous-tests.test.ts
source/rules/no-synchronous-tests.ts

The `no-synchronous-tests` rule should apply to tests and hooks, not suites.
This PR fixes the issue by checking the type of the context when visiting it within the rule.
Fixes #399

Fix handling of suites in no-synchronous-tests
