lo1tuma/eslint-plugin-mocha

README.md

It took me quite a while to figure out how to successfully activate this precious rule.
I hope this saves everyone else some time : )

Add install documentation to README

---

docs/rules/README.md
docs/rules/no-global-tests.md
index.js
lib/rules/no-global-tests.js
test/rules/no-global-tests.js

Implement new rule no-global-tests

---

.eslintrc
package.json
test/index.js
test/rules/handle-done-callback.js
test/rules/no-global-tests.js
test/rules/no-synchronous-tests.js

Hi there!
I am working with latest eslint and wanted to use this as a plugin. This is a PR to fix it for the upcoming 2.0 of ESlint.
It should have a major bump of version number. But that can be done once #48 is done (which I can happily try to do).

Update to eslint 2.0.0

---

docs/rules/handle-done-callback.md
docs/rules/no-exclusive-tests.md
docs/rules/no-skipped-tests.md
lib/rules/handle-done-callback.js
lib/rules/no-exclusive-tests.js
lib/rules/no-global-tests.js
lib/rules/no-skipped-tests.js
lib/rules/no-synchronous-tests.js
test/rules/handle-done-callback.js
test/rules/no-exclusive-tests.js
test/rules/no-global-tests.js
test/rules/no-skipped-tests.js
test/rules/no-synchronous-tests.js

Support specify alias

---

docs/rules/no-exclusive-tests.md

update to docs to match removed autofix

---

docs/rules/README.md

Additional followup from https://github.com/lo1tuma/eslint-plugin-mocha/pull/63

Remove fixable from no-exclusive on README

---

.travis.yml

Drop support old node versions

---

index.js

Add recommended config

---

docs/rules/README.md
docs/rules/no-hooks.md
index.js
lib/rules/no-hooks.js
test/rules/no-hooks.js

Add rule `no-hooks` (fixes #39)
Let me know if you want me to change something or if I've missed something :)

Add rule `no-hooks` (fixes #39)

---

docs/rules/no-sibling-hooks.md

Fix title in `no-sibling-hooks` documentation file

Fix title in `no-sibling-hooks` documentation file

---

docs/rules/README.md
docs/rules/no-hooks-for-single-case.md
index.js
lib/rules/no-hooks-for-single-case.js
lib/util/ast.js
test/rules/no-hooks-for-single-case.js

Add `no-hooks-for-single-case` rule (fixes #44)

Add `no-hooks-for-single-case` rule (fixes #44)

---

docs/rules/valid-test-description.md

Adds rule name to title for `valid-test-description` documentation.

---

lib/rules/no-exclusive-tests.js
lib/util/ast.js
test/rules/no-exclusive-tests.js

Support MemberExpression for additionalTestFunctions

---

docs/rules/README.md

Just ran through a project where I needed to reference this list and had to keep scanning the whole list to find the rule. This change should simplify that process.

Organize alphabetically

---

package.json
test/rules/no-mocha-arrows.js

This updates the peer dependency to ESLint to be also compatible with ESLint 4.x.

Support ESLint 4.x

---

lib/rules/handle-done-callback.js
lib/rules/no-global-tests.js
lib/rules/no-mocha-arrows.js
lib/rules/no-nested-tests.js
lib/rules/no-pending-tests.js
lib/rules/no-return-and-callback.js
lib/rules/no-sibling-hooks.js
lib/rules/no-skipped-tests.js
lib/rules/valid-suite-description.js
lib/rules/valid-test-description.js
lib/util/ast.js
test/rules/no-mocha-arrows.js

This refactors some rules and ast utils to reduce the cyclomatic complexity.
Fixes #148.

Fix complexity problems

---

package.json
test/index.js

Update chai to version 4.1.2

---

lib/rules/no-setup-in-describe.js
test/rules/no-setup-in-describe.js

Issue #166: No setup in describe hooks

---

package.json

Update nyc to version 12.0.2

---

package.json

Update eslint to version 5.0.1

---

.travis.yml

Add node 10 build environment

---

lib/util/ast.js
test/rules/no-setup-in-describe.js

Fix no-setup-in-describe to allow mocha config calls

---

lib/util/ast.js
test/rules/no-setup-in-describe.js

Support TDD interface in no-setup-in-describe

---

README.md

[![GitHub Actions status](https://github.com/lo1tuma/eslint-plugin-mocha/workflows/CI/badge.svg)](https://github.com/lo1tuma/eslint-plugin-mocha/actions)

♻️ Replace Travis build badge with GitHub Actions badge

---

package-lock.json

Adding npm-recommended (and now auto-generated) `package-lock.json` to repo.
If you'd prefer, I can add to `.gitignore` instead.

- npm: Add package-lock.json

---

docs/rules/no-synchronous-tests.md

- Fix doc issue impacting highlighting (a function example in no-synchronous tests needed to close a parenthesis)

Doc syntax issue

---

docs/rules/no-hooks.md
lib/rules/no-hooks.js
test/rules/no-hooks.js

no-hooks: add option to allow certain kind of hooks

---

lib/rules/max-top-level-suites.js
test/rules/max-top-level-suites.js

Fix max-top-level-suites to ignore generated suites

---

.eslintrc.json
docs/rules/handle-done-callback.md
lib/rules/handle-done-callback.js
lib/util/ast.js
lib/util/names.js
test/rules/handle-done-callback.js
test/util/namesSpec.js

New option `ignoreSkipped` for `handle-done-callback` rule

---

lib/rules/prefer-arrow-callback.js

I tend to watch for issues in projects of interest at https://lgtm.com (theirs is a useful service to add for PRs by the way), and came across this issue.
See https://lgtm.com/projects/g/lo1tuma/eslint-plugin-mocha/?mode=list

- Avoid passing superfluous argument

---

lib/rules/no-setup-in-describe.js
test/rules/no-setup-in-describe.js

Fix false positive in no-setup-in-describe

---

docs/rules/README.md
index.js

Turn off no-hooks-for-single-case in recommended

---

lib/rules/no-empty-description.js
test/rules/no-empty-description.js

Fix no-empty-description rule to not report on dynamic values

---

lib/rules/no-empty-description.js
test/rules/no-empty-description.js

Allow dynamic expressions as description argument in no-empty-description

---

.eslintrc.json
benchmarks/measure.js
package-lock.json
package.json

Hello, 
I upgraded packages so the vulnerability issues caused by old versions went away.
Is it needed anything else to make this PR merged?
Thanks
Jan

Bump package versions due to vulnerability issues

---

index.js

See https://eslint.org/docs/latest/use/configure/configuration-files#configuration-naming-conventions and eg https://github.com/eslint-community/eslint-plugin-eslint-plugin/pull/459
Improves presentation in the config inspector: https://github.com/eslint/config-inspector

Add name to flat configs

---

README.md
docs/rules/no-empty-title.md
docs/rules/valid-suite-title.md
docs/rules/valid-test-title.md
index.js
lib/rules/no-empty-title.js
lib/rules/valid-suite-title.js
lib/rules/valid-test-title.js
test/rules/no-empty-title.js
test/rules/valid-suite-title.js
test/rules/valid-test-title.js

Rename *-description rules to *-title

---

.c8rc.json
source/rules/no-setup-in-describe.test.ts
source/rules/no-setup-in-describe.ts

Fix detecting mocha config calls in no-setup-in-describe

---

source/rules/no-identical-title.test.ts

Add test to verify no-identical-title supports same titles in different suites
